//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicTacToe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 X 10 (5).
        /// </summary>
        internal static string Board10x10With5inRow {
            get {
                return ResourceManager.GetString("Board10x10With5inRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 X 3 (3).
        /// </summary>
        internal static string Board3x3With3inRow {
            get {
                return ResourceManager.GetString("Board3x3With3inRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 X 5 (5).
        /// </summary>
        internal static string Board5x5With5inRow {
            get {
                return ResourceManager.GetString("Board5x5With5inRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⨯.
        /// </summary>
        internal static string Cross {
            get {
                return ResourceManager.GetString("Cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over. Draw.
        /// </summary>
        internal static string DrawMessage {
            get {
                return ResourceManager.GetString("DrawMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stupid Randomizer AI.
        /// </summary>
        internal static string DummyAI {
            get {
                return ResourceManager.GetString("DummyAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string HumanPlayer {
            get {
                return ResourceManager.GetString("HumanPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intuitive AI.
        /// </summary>
        internal static string IntuitiveAI {
            get {
                return ResourceManager.GetString("IntuitiveAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimax AI.
        /// </summary>
        internal static string MinimaxPlayer {
            get {
                return ResourceManager.GetString("MinimaxPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} made move.
        /// </summary>
        internal static string MoveMessage {
            get {
                return ResourceManager.GetString("MoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ○.
        /// </summary>
        internal static string Nought {
            get {
                return ResourceManager.GetString("Nought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimized Minimax AI.
        /// </summary>
        internal static string OptimizedMinimaxPlayer {
            get {
                return ResourceManager.GetString("OptimizedMinimaxPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s {0} turn.
        /// </summary>
        internal static string TurnMessage {
            get {
                return ResourceManager.GetString("TurnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over. Player {0} win!.
        /// </summary>
        internal static string WinMessage {
            get {
                return ResourceManager.GetString("WinMessage", resourceCulture);
            }
        }
    }
}
